name: md5-CI-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  DLL_NAME: haine

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: release-build
        shell: pwsh
        run: |
          .\build.bat
      - name: disable auto crlf
        uses: steve02081504/disable-autocrlf@v1
      - name: updates build
        uses: Taromati2/ukagaka-mirror-md5-CI-build@v1
        with:
          no-push: true
          build-mode: other
      - name: git push
        # commit and push all changes at once to avoid error
        run: |
          git config --local user.email "calcium629@gmail.com"
          git config --local user.name "apxxxxxxe"
          git config --local core.safecrlf off
          git add .
          git status
          git commit -m "update md5, dll and surfaces.txt" -a
          git pull
          git push
